language: minimal

cache:
  directories:
  - /home/travis/docker

before_install:
- docker load -i /home/travis/docker/images.tar || true

install:
- docker build . -t nztrain:latest

script:
- > 
  docker run --privileged --network host 
  --env-file <(env | grep TRAVIS)
  nztrain:latest /bin/bash -c "
  service redis start;
  service postgresql start;
  bundle exec rake db:test:load; 
  bundle exec rspec"

before_cache:
- docker save -o /home/travis/docker/images.tar $(docker images -a -q)

