language: minimal

cache:
  directories:
  - docker

before_install:
- docker load -i docker/images.tar || true

install:
- docker build . -t nztrain:latest

script:
- > 
  docker run --privileged --network host 
  --env-file <(env) nztrain:latest 
  /bin/bash -c "
  service redis start;
  service postgresql start;
  bundle exec rake db:test:load; 
  bundle exec rspec"

before_cache:
- docker save -o docker/images.tar $(docker images -a -q)

