require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AiContestsController do

  # This should return the minimal set of attributes required to create a valid
  # AiContest. As you add validations to AiContest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AiContestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ai_contests as @ai_contests" do
      ai_contest = AiContest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ai_contests).should eq([ai_contest])
    end
  end

  describe "GET show" do
    it "assigns the requested ai_contest as @ai_contest" do
      ai_contest = AiContest.create! valid_attributes
      get :show, {:id => ai_contest.to_param}, valid_session
      assigns(:ai_contest).should eq(ai_contest)
    end
  end

  describe "GET new" do
    it "assigns a new ai_contest as @ai_contest" do
      get :new, {}, valid_session
      assigns(:ai_contest).should be_a_new(AiContest)
    end
  end

  describe "GET edit" do
    it "assigns the requested ai_contest as @ai_contest" do
      ai_contest = AiContest.create! valid_attributes
      get :edit, {:id => ai_contest.to_param}, valid_session
      assigns(:ai_contest).should eq(ai_contest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AiContest" do
        expect {
          post :create, {:ai_contest => valid_attributes}, valid_session
        }.to change(AiContest, :count).by(1)
      end

      it "assigns a newly created ai_contest as @ai_contest" do
        post :create, {:ai_contest => valid_attributes}, valid_session
        assigns(:ai_contest).should be_a(AiContest)
        assigns(:ai_contest).should be_persisted
      end

      it "redirects to the created ai_contest" do
        post :create, {:ai_contest => valid_attributes}, valid_session
        response.should redirect_to(AiContest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ai_contest as @ai_contest" do
        # Trigger the behavior that occurs when invalid params are submitted
        AiContest.any_instance.stub(:save).and_return(false)
        post :create, {:ai_contest => {}}, valid_session
        assigns(:ai_contest).should be_a_new(AiContest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AiContest.any_instance.stub(:save).and_return(false)
        post :create, {:ai_contest => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ai_contest" do
        ai_contest = AiContest.create! valid_attributes
        # Assuming there are no other ai_contests in the database, this
        # specifies that the AiContest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AiContest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ai_contest.to_param, :ai_contest => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ai_contest as @ai_contest" do
        ai_contest = AiContest.create! valid_attributes
        put :update, {:id => ai_contest.to_param, :ai_contest => valid_attributes}, valid_session
        assigns(:ai_contest).should eq(ai_contest)
      end

      it "redirects to the ai_contest" do
        ai_contest = AiContest.create! valid_attributes
        put :update, {:id => ai_contest.to_param, :ai_contest => valid_attributes}, valid_session
        response.should redirect_to(ai_contest)
      end
    end

    describe "with invalid params" do
      it "assigns the ai_contest as @ai_contest" do
        ai_contest = AiContest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AiContest.any_instance.stub(:save).and_return(false)
        put :update, {:id => ai_contest.to_param, :ai_contest => {}}, valid_session
        assigns(:ai_contest).should eq(ai_contest)
      end

      it "re-renders the 'edit' template" do
        ai_contest = AiContest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AiContest.any_instance.stub(:save).and_return(false)
        put :update, {:id => ai_contest.to_param, :ai_contest => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ai_contest" do
      ai_contest = AiContest.create! valid_attributes
      expect {
        delete :destroy, {:id => ai_contest.to_param}, valid_session
      }.to change(AiContest, :count).by(-1)
    end

    it "redirects to the ai_contests list" do
      ai_contest = AiContest.create! valid_attributes
      delete :destroy, {:id => ai_contest.to_param}, valid_session
      response.should redirect_to(ai_contests_url)
    end
  end

end
